name: Build and publish docker image
on:
  schedule:
    - cron: '0 0 1 */2 *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup binfmt
        run: |
          sudo apt update -y
          sudo apt install qemu-user-static -y
      # - name: login to docker hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build and push to docker hub
      #   run: |
      #     docker build --tag rebornos/rebornos-arm:latest . --network=host --platform linux/arm64
      #     docker push rebornos/rebornos-arm:latest
      - name: Login into ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to ghcr.io
        run: |
          docker build --tag ghcr.io/rebornos-developers/rebornos-arm:latest . --network=host --platform linux/arm64
          docker push ghcr.io/rebornos-developers/rebornos-arm:latest
          